version: "3.4"

services:
  local-redis-service:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]

  web:
    depends_on:
      local-redis-service:
        condition: service_healthy
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: sh ./scripts/start.sh